name: FF-Cloud-Bot
on:
  schedule:
    - cron: '*/10 * * * *' # Ye bot ko har 10 minute mein apne aap chalayega
  workflow_dispatch: # Isse aap manually bhi start kar sakte ho

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Requests
        run: pip install requests
      - name: Run Glory Bot
        run: python bot.py
run.yml
